##### Vars inherits from root #####
ROOT_DIR := ..
include ${ROOT_DIR}/tools/makefiles/vars.Makefile

include ${ROOT_DIR}/tools/makefiles/colors.Makefile
include ${ROOT_DIR}/tools/makefiles/helpers.Makefile

DOCKER_WORKING_DIRECTORY = ${DATA_PATH_PREFIX}/ui

include tools/makefiles/control.Makefile
include tools/makefiles/test.Makefile
include tools/makefiles/dependency.Makefile
include tools/makefiles/install.Makefile
include tools/makefiles/ci.Makefile
